import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ImportSupervisor } from "@/components/imports/ImportSupervisor";
import { ImportQueueProvider } from "@/context/ImportQueueContext";
import { ActiveOpponentProvider } from "@/context/ActiveOpponentContext";
import { OnboardingProvider } from "@/context/OnboardingContext";
import { GlobalNavBar } from "@/components/nav/GlobalNavBar";
import { NavPaddingWrapper } from "@/components/nav/NavPaddingWrapper";
import { MaintenanceScreen } from "@/components/maintenance/MaintenanceScreen";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseServiceClient } from "@/lib/supabase/service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ADMIN_EMAILS = [process.env.NEXT_PUBLIC_ADMIN_EMAIL, "jeff.kern@gmail.com"].filter(Boolean) as string[];

function normalizeEmail(email: string | null | undefined): string {
  return String(email ?? "").trim().toLowerCase();
}

async function getMaintenanceMode(): Promise<{ enabled: boolean; message: string | null }> {
  try {
    const supabase = createSupabaseServiceClient();
    const { data, error } = await supabase
      .from("app_settings")
      .select("key, value")
      .in("key", ["maintenance_mode_enabled", "maintenance_mode_message"]);

    if (error) {
      return { enabled: false, message: null };
    }

    const byKey = new Map((data ?? []).map((r: any) => [String(r.key), r] as const));
    const enabled = String((byKey.get("maintenance_mode_enabled") as any)?.value ?? "")
      .trim()
      .toLowerCase();
    const message = String((byKey.get("maintenance_mode_message") as any)?.value ?? "");

    return {
      enabled: enabled === "true" || enabled === "1" || enabled === "yes",
      message,
    };
  } catch {
    // If service role env vars are not configured, fail open.
    return { enabled: false, message: null };
  }
}

async function isAdminUser(): Promise<boolean> {
  try {
    const supabase = await createSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    const email = normalizeEmail(user?.email);
    if (!email) return false;
    return ADMIN_EMAILS.some((adminEmail) => normalizeEmail(adminEmail) === email);
  } catch {
    return false;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [{ enabled: maintenanceEnabled, message }, admin] = await Promise.all([
    getMaintenanceMode(),
    isAdminUser(),
  ]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {maintenanceEnabled && !admin ? (
          <MaintenanceScreen message={message} />
        ) : (
          <>
            <ImportSupervisor />
            <ImportQueueProvider>
              <ActiveOpponentProvider>
                <OnboardingProvider>
                  <GlobalNavBar />
                  <NavPaddingWrapper>{children}</NavPaddingWrapper>
                </OnboardingProvider>
              </ActiveOpponentProvider>
            </ImportQueueProvider>
          </>
        )}
      </body>
    </html>
  );
}
