import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ImportSupervisor } from "@/components/imports/ImportSupervisor";
import { ImportQueueProvider } from "@/context/ImportQueueContext";
import { ActiveOpponentProvider } from "@/context/ActiveOpponentContext";
import { OnboardingProvider } from "@/context/OnboardingContext";
import { GlobalNavBar } from "@/components/nav/GlobalNavBar";
import { NavPaddingWrapper } from "@/components/nav/NavPaddingWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ImportSupervisor />
        <ImportQueueProvider>
          <ActiveOpponentProvider>
            <OnboardingProvider>
              <GlobalNavBar />
              <NavPaddingWrapper>{children}</NavPaddingWrapper>
            </OnboardingProvider>
          </ActiveOpponentProvider>
        </ImportQueueProvider>
      </body>
    </html>
  );
}
